Ревью 10 спринта
alex-tsidilin/ImageFeed pull request #2
Opened 2023-01-11 18:49 UTC by alex-tsidilin

- Ваше приложение зарегистрировано на сайте Unsplash.
- Экран авторизации содержит логотип приложения и кнопку «Войти». 
- Для входа в приложение пользователь авторизуется через OAuth2.0 
- В проекте создан файл Constants.swift, в нём есть константы AccessKey, SecretKey, RedirectURI и AccessScope 
- Свёрстан контроллер WebView, его дизайн соответствует ТЗ 
- Реализован KVO — приложение показывает, как обновляется прогресс загрузки веб-страницы 
- Проверка необходимости авторизации выделена в отдельный контроллер SplashViewController 
- Добавлена структура для декодинга JSON-ответа от POST-запроса авторизации Unsplash — OAuthTokenResponseBody 
- Создан новый класс OAuth2Service

2023-01-12 18:22 UTC, IBDesignable requested changes

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +    let ShowWebViewSegueIdentifier = "ShowWebView"
это свойство, поэтому настаиваю на соблюдении правила camelCase

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +    @IBOutlet weak var authButton: UIButton!
Давай проверим приватность всех методов и свойств, и будем придерживаться этой идее и в других классах тоже

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +        delegate?.authViewController(self, didAuthenticateWithCode: code)
Здесь, я ожидаю увидеть код, который получит токен и результат этой работы сообщит своему далегату. 
Получение токена - часть авторизации, поэтому логично выполнять эту работу здесь. 

> В классе `AuthViewController`, там, где вызывается метод делегата `webViewViewController(_ vc: WebViewViewController, didAuthenticateWithCode code: String)`, вызван `fetchAuthToken`

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/OAuth2Service.swift
> +    func fetchAuthToken(code: String, completion: @escaping (Result<String, Error>) -> Void){
```suggestion
    func fetchAuthToken(code: String, completion: @escaping (Result<String, Error>) -> Void) {
```

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +    override func viewDidLoad() {
пропущен вызов метод родителя (super. viewDidLoad)

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +        // In case of inhertiance context must not be nil.
уберем лишние комменты?

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Constants/Constants.swift
> +
Такие штуки в продакшене принято обрамлять пустым енамом:

```
enum Constants {
    static let accessKey = ""
}
```

Вызов: `Constants.accessKey`

Обычно глобальный контекст избегают

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Controllers/SplashViewController.swift
> +    private let ShowAuthenticationScreenSegueIdentifier = "ShowAuthenticationScreen"
Здесь тоже бы в camelCase

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Controllers/SplashViewController.swift
> +    //MARK: - Methods
давай договоримся не больше одной пустой строки оставлять между логическими блоками

2023-01-12 18:22 UTC, IBDesignable commented on ImageFeed/Controllers/SplashViewController.swift
> +        dismiss(animated: true) { [weak self] in
Этот метод вызывается у SplashViewController. Аналогично вызову self.dismiss(animated: true). 

Это немного бессмысленно, потому что контроллер рутовый, поэтому вероятно здесь хотелось сделать дисмис на AuthViewController и он бы тогда скрылся и это бы имело смысл

2023-01-12 18:35 UTC, ABashkirova commented on ImageFeed/Auth/AuthViewController.swift
> +    @IBOutlet weak var authButton: UIButton!
Давай проверим приватность всех методов и свойств

2023-01-12 18:35 UTC, ABashkirova commented on ImageFeed/Auth/AuthViewController.swift
> +    let ShowWebViewSegueIdentifier = "ShowWebView"
это свойство, поэтому настаиваю на соблюдении правила camelCase

2023-01-17 14:05 UTC, IBDesignable requested changes

2023-01-17 14:05 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +    private let splashViewController = SplashViewController()
Нет, давай не будем создавать и тем более сильно держать ссылку на вью контроллер. 

Он у тебя в иерархии уже есть, надо лишь правильно на него возвращаться с экрана авторизации (комменты ниже)

2023-01-17 14:05 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    self.splashViewController.switchToTabBarController()
вот здесь достаточно вернуть делегату знания о том, что авторизация закончилась (код не обязательно дальше передавать, но можно передать результат успешно/не успешно. 

На сколько я понимаю, делегата реализуешь сплеш скрин. Вот он и будет принимать решение о том что нужно свитчеваться на таббар. А то слишком много ответственности у экрана авторизации получилось

2023-01-17 14:05 UTC, IBDesignable commented on ImageFeed/Controllers/SplashViewController.swift
> +        dismiss(animated: true)
Здесь метод `dismiss` вызывается на self, этот метод пытается закрыть экран на котором все запущено, то есть SplashScreen. (как бы схлопывает всю цепочку созданных экранов в навигации)

А хотелось бы, чтобы закрывал AuthViewController, поэтому на нем его и стоит вызывать: vc.dismiss(animated: true) 

При этом, учитывая комментарии выше, здесь как раз надо принять решение о том нужно ли идти дальше (свичнуться) или токена нет и нам бы наоборот вернуться к авторизации. 

Это принципиальные моменты в этом спринте, поэтому попрошу доработать, хотя возможно в чек-листе этого и не просили делать явно. , если ты напи

Также, буду благодарна, если напишешь мне или Наставнику пару строк с фидбеком про этот спринт, как понял и почему не получилось сделать сразу так. Я вижу сложности с этим местом возникают не только у тебя. Может быть в учебнике не достаточно хорошо про это рассказали и мы можем улучшить это место. 🙏🏻

2023-01-21 18:13 UTC, merged

2023-01-22 11:36 UTC, IBDesignable commented on ImageFeed/Controllers/SplashViewController.swift
> +    let tokenStorage = OAuth2TokenStorage()
Есть причины не делать приватным?

2023-01-22 11:36 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
>                      print(error)
На будущий спринт: эта строчка место для возможного вызов нового метода делегата, чтобы сообщить об ошибке

2023-01-22 11:38 UTC, alex-tsidilin commented on ImageFeed/Controllers/SplashViewController.swift
> +    let tokenStorage = OAuth2TokenStorage()
Проверял одну зависимость и забыл вернуть когда отправлял пул реквест, уже вернул обратно